project/tools/squirrel/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('',views.index),
        path('sightings/', views.all_squirrels),
        path('sightings/stats/', views.stats),
        path('sightings/add/', views.add_squirrel, name='add'),
        path('sightings/<unique_squirrel_ID>/', views.update_squirrel, name='update'),
        path('map/', views.map,name='map'),
  ]

squirrel/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('sightings/', views.all_squirrels),
        path('sightings/add/', views.add_squirrel,name='add'),
        path('sightings/<unique_squirrel_ID>/', views.update_squirrel,name='update'),
        path('map/', views.map,name='map'),
  ]

tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include(('squirrel.urls','squirrel'), namespace='squirrel')),
    path('admin/', admin.site.urls),
]

squirrel/models.py
from django.db import models

from django.utils.translation import gettext as _

class Squirrel(models.Model):
    latitude = models.FloatField(
            max_length = 100,
    )


    longitude = models.FloatField(
            max_length = 100,
    ) 

    ID = models.CharField(
            max_length = 100,
            primary_key = True,
    )     

    PM = 'PM'
    AM = 'AM'

    SHIFT_CHOICES = (
            (PM, 'PM'),
            (AM, 'AM'),
    )

    shift = models.CharField(
            max_length = 8,
            choices=SHIFT_CHOICES,
            default=AM
    )

    date = models.DateField(
    )

    ADULT = 'Adult'
    JUVENILE = 'Juvenile'

    AGE_CHOICES = (
            (ADULT, 'Adult'),
            (JUVENILE, 'Juvenile'),
    )

    age = models.CharField(
            max_length = 100,
            choices=AGE_CHOICES,
            blank=True
    )

    BLACK = 'Black'
    GRAY = 'Gray'
    CINNAMON = 'Cinnamon'

    COLOR_CHOICES = (
            (BLACK, 'Black'),
            (GRAY, 'Gray'),
            (CINNAMON, 'Cinnamon'),
    )

    primary_fur_color = models.CharField(
            max_length = 100,
            choices=COLOR_CHOICES,
            blank=True
    )
    
    GROUND = 'Ground Plane'
    ABOVE = 'Above Ground'

    LOCATION_CHOICES = (
            (GROUND, 'Ground Plane'),
            (ABOVE, 'Above Ground'),
    )

    location = models.CharField(
            max_length = 100,
            choices=LOCATION_CHOICES,
            blank=True
    )

    specific_location = models.CharField(
            max_length = 100,
            blank=True
    )

    running = models.BooleanField(
            default=False)

    chasing = models.BooleanField(
            default=False)

    climbing = models.BooleanField(
            default=False)

    eating = models.BooleanField(
            default=False)

    foraging = models.BooleanField(
            default=False)

    other_activities = models.CharField(
            max_length = 100,
            blank = True
    )

    kuks = models.BooleanField(
            default=False)

    quaas = models.BooleanField(
            default=False)

    moans = models.BooleanField(
            default=False)

    tail_flags = models.BooleanField(
            default=False)

    tail_twitches = models.BooleanField(
            default=False)

    approaches = models.BooleanField(
            default=False)

    indifferent = models.BooleanField(
            default=False)

    runs_from = models.BooleanField(
            default=False)

squirrel/forms.py
from django.forms import ModelForm

from .models import Squirrel

class SquirrelForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = '__all__'

project/tools/squirrel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from django.db.models import Count

from .models import Squirrel
from .forms import SquirrelForm

def index(request):
    return render(request, 'squirrel/index.html')

def all_squirrels(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels' : squirrels,
    }
    return render(request, 'squirrel/all.html', context)

def add_squirrel(request):
    if request.method == 'POST':
        form = SquirrelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/sightings/')
    else:
        form = SquirrelForm()

    context = {
            'form': form,
            'jazz': True,
    }

    return render(request, 'squirrel/edit.html', context)

def update_squirrel(request,unique_squirrel_ID):
    squirrel = Squirrel.objects.get(ID=unique_squirrel_ID)
    if request.method == 'POST':
        form = SquirrelForm(request.POST, instance=squirrel)
        if form.is_valid():
            form.save()
            return redirect('/sightings/')
    else:
        form = SquirrelForm(instance=squirrel)

    context = {
        'form': form,
    }

    return render(request, 'squirrel/edit.html', context)

def map(request):
    squirrels = Squirrel.objects.order_by('?')[:100]
    context = {
            'squirrels':squirrels,
    }
    return render(request, 'squirrel/map.html', context)

def stats(request): 
    total_count = Squirrel.objects.all().count() 
    running_true = Squirrel.objects.filter(running=True).count() 
    running_false = Squirrel.objects.filter(running=False).count() 
    running_pct = "{:.2%}".format(running_true/total_count) 
    chasing_true = Squirrel.objects.filter(chasing=True).count() 
    chasing_false = Squirrel.objects.filter(chasing=False).count() 
    chasing_pct = "{:.2%}".format(chasing_true/total_count) 
    climbing_true = Squirrel.objects.filter(climbing=True).count() 
    climbing_false = Squirrel.objects.filter(climbing=False).count() 
    climbing_pct = "{:.2%}".format(climbing_true/total_count) 
    eating_true = Squirrel.objects.filter(eating=True).count() 
    eating_false = Squirrel.objects.filter(eating=False).count() 
    eating_pct = "{:.2%}".format(eating_true/total_count) 
    foraging_true = Squirrel.objects.filter(foraging=True).count() 
    foraging_false = Squirrel.objects.filter(foraging=False).count() 
    foraging_pct = "{:.2%}".format(foraging_true/total_count) 
    context = { 
            'total_count' : total_count, 
            'running_true' : running_true, 
            'running_false' : running_false, 
            'running_pct' : running_pct, 
            'chasing_true' : chasing_true, 
            'chasing_false': chasing_false, 
            'chasing_pct' : chasing_pct, 
            'climbing_true' : climbing_true, 
            'climbing_false': climbing_false, 
            'climbing_pct' : climbing_pct, 
            'eating_true' : eating_true, 
            'eating_false': eating_false, 
            'eating_pct' : eating_pct, 
            'foraging_true' : foraging_true, 
            'foraging_false': foraging_false, 
            'foraging_pct' : foraging_pct, 
            } 
    return render(request, 'squirrel/stats.html',context)

squirrel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect

from .models import Squirrel
from .forms import SquirrelForm

def all_squirrels(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels' : squirrels,
    }
    return render(request, 'squirrel/all.html', context)

def add_squirrel(request):
    if request.method == 'POST':
        form = SquirrelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(f'/sightings/')
    if request.method == 'GET':
        form = SquirrelForm(request.GET)
        if form.is_valid():
            form.save()
            return resirect(f'/sighings/')
    else:
        form = SquirrelForm()

    context = {
            'form': form,
            'jazz': True,
    }

    return render(request, 'squirrel/edit.html', context)

def update_squirrel(request,unique_squirrel_ID):
    squirrel = Squirrel.objects.get(ID=unique_squirrel_ID)
    if request.method == 'POST':
        form = SquirrelForm(request.POST, instance=squirrel)
        if form.is_valid():
            form.save()
            return redirect(f'/sightings/')
    else:
        form = SquirrelForm(instance=squirrel)

    context = {
        'form': form,
    }

    return render(request, 'squirrel/edit.html', context)

def map(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels':squirrels,
    }
    return render(request, 'squirrel/map.html', context)

project/tools/squirrel/templates/squirrel/all.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </br>
  <h2><center>Sightings of Squirrels<center></h2>
  </br>
</head>
<body>
  <center>	
  <a href="add/" class="btn btn-primary btn-lg" role="button">Add a New Squirrel</a>
  <a href="stats/" class="btn btn-primary btn-lg" role="button" >Summary of Sightings</a>
  </center>
  </br>
  <div class="list-group">
  <center>
  {% for squirrel in squirrels %}
  <a href ={% url 'squirrel:update' squirrel.ID %} class="list-group-item list-group-item-action">{{ squirrel.ID }}</a>
  {% endfor %}
  </center>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

project/tools/squirrel/templates/squirrel/edit.html
<!doctype html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </br>
    <h2><center>Squirrel Form</center></h2>
    </br>
  <body>
    <center>
    <form method="post">
      {% csrf_token %}
      
      {{ form.as_p }}
      <br>
      <input type="submit" name="Submit">
    </form>
    </center>
    </br></br>
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  
  </body>
</html>

project/tools/squirrel/templates/squirrel/index.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </br>
    <h2><center>Squirrels</center></h2>
    </br>
</head>
<body>
  <center>
  <a href="sightings/" class="btn btn-primary btn-lg" role="button">Sightings</a>
  <a href="map/" class="btn btn-primary btn-lg" role="button">Map</a>
  </center>
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

project/tools/squirrel/templates/squirrel/stats.html
<!doctype html>
<html>
<head>
  <meta charset = 'utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </br>
  <title>Summary of Sightings</title>
  <h2><center>Summary of Sightings<center></h2>
</head>
<body>
  <p><center>Total Number of Sightings: {{ total_count }}<center></p>
  <p><table class="table table-striped">
    <tr>
      <th></th>
      <th>True</th>
      <th>False</th>
      <th>Pct.</th>
    </tr>
    <tr>
      <th scope="row">Running</th>	    
      <td>{{ running_true }}</td>
      <td>{{ running_false }}</td>
      <td>{{ running_pct }}</td>
    </tr>
    <tr>
      <th scope='row'>Chasing</th>	    
      <td>{{ chasing_true }}</td>
      <td>{{ chasing_false }}</td>
      <td>{{ chasing_pct }}</td>
    </tr>
    <tr>
      <th scope='row'>Climbing</th>
      <td>{{ climbing_true }}</td>
      <td>{{ climbing_false }}</td>
      <td>{{ climbing_pct }}</td>
    </tr>
    <tr>
      <th scope='row'>Eating</th>
      <td>{{ eating_true }}</td>
      <td>{{ eating_false }}</td>
      <td>{{ eating_pct }}</td>
    </tr>
    <tr>
      <th scope='row'>Foraging</th>
      <td>{{ foraging_true }}</td>
      <td>{{ foraging_false }}</td>
      <td>{{ foraging_pct }}</td>
    </tr>
  </table></p>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

squirrel/templates/squirrel/all.html
<!doctype html>
<html>
  <head>
    <title>"All Sightings of Squirrels"</title>
  </head>
  <body>
  <a href="add/">>Add a New Squirrel</a>
  {% for squirrel in squirrels %}
  <li><a href ={% url 'squirrel:update' squirrel.ID %}>{{ squirrel.ID }}</a></li>
  {% endfor %}
  </body>
</html>

squirrel/templates/squirrel/edit.html
<!doctype html>
<html>
  <body>
    <form method="post">
      {% csrf_token %}
      
      {{ form.as_p }}
      <br>
      <input type="submit" name="Submit">
    </form>
  </body>
</html>

squirrel/templates/squirrel/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for squirrel in squirrels %}
          var point_lat_lon = [{{ squirrel.latitude }}, {{ squirrel.longitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>